[general]
import = [
    "~/.config/alacritty/themes/themes/argonaut.toml"
]

[env]
# TODO: Figure all of this shit out!
#
# This is needed to get ssh colours on remote hosts
# TERM = "xterm-256-color"
# TERM = "trucolour"


[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
blur = true

# option_as_alt = "Both"

[window.padding]
x = 5
y = 5


[font]
size = 13
# draw_bold_text_with_bright_colors = true

# [font.bold]
# family = "SFMono Nerd Font"
#
# [font.bold_italic]
# family = "SFMono Nerd Font"
#
#
# [font.italic]
# family = "SFMono Nerd Font"
#
# [font.normal]
# family = "SFMono Nerd Font"

# MesloLGM Nerd Font Mono

[font.bold]
family = "MesloLGM Nerd Font Mono"

[font.bold_italic]
family = "MesloLGM Nerd Font Mono"


[font.italic]
family = "MesloLGM Nerd Font Mono"

[font.normal]
family = "MesloLGM Nerd Font Mono"


[colors]
cursor = { text = "CellBackground", cursor = "#ab352f" }

[colors.primary]
background = "#131c28"

# [colors.selection]
# text = "CellForeground"  # This keeps the selected text the same color as the foreground.
# # background = "#c6dcfc"   # Set the background color for selections.
# background = "CellForeground"   # Set the background color for selections.
