excluded_dirs = ["Users/jimbo/Code/_old", "Users/jimbo/uni/4041/ECPending_cw-yield-20424504"]

[[search_dirs]]
path = "~/Code"
depth = 3

[[search_dirs]]
path = "~/uni/4041"
depth = 3

[[search_dirs]]
path = "~/uni/3007"
depth = 3

[[search_dirs]]
path = "~/uni/3011"
depth = 3

[[search_dirs]]
path = "~/uni/3006"
depth = 3

[[search_dirs]]
path = "~/.config"
depth = 0

[[search_dirs]]
path = "~/scripts"
depth = 0

