-- -- -- Set up custom highlight groups for completion items
-- vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#FFFFFF" })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = "#569CD6", bold = true })
-- vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = "#569CD6", underline = true })
-- vim.api.nvim_set_hl(0, "CmpItemKind", { fg = "#C586C0" })
-- vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#9CDCFE", italic = true })
